name: "infra preview & deploy"

on:
  push:
    branches:
    - main
    path:
    - 10_infra/**
    - github/workflows/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  
jobs:
  preview:
    name: "Preview"
    steps:
      - run: |
        echo "Hello World"
